// Generated by GuardStep. Do not edit manually.
// Generator: GuardStep 0.1.0-alpha.1
// Source: decide.guard
// Source SHA-256: sha256:9ee78af661506b1138986bf6c62c64edd62b3fda61136399ab39bfb9c3b73c04

import type { Pricing as __GuardStepPricing } from "guardstep/runtime";

export type Failure =
  | "EMPTY"
  | "DENIED"
  | "TIMEOUT"
  | "ERROR"
  | "INVALID"
  | "DURATION"
  | "COST";

export interface Message {
  readonly "text": string;
}

export interface EchoToolInvocation {
  readonly runId: string;
  readonly stepId: string;
  readonly tool: "echo";
  readonly arguments: {
    readonly "text": string;
  };
  readonly signal: AbortSignal;
}

export type EchoToolResult =
  | {
      readonly status: "succeeded";
      readonly value: Message;
      readonly elapsedMs: number;
      readonly eventData?: Readonly<Record<string, unknown>>;
    }
  | {
      readonly status: "failed";
      readonly kind: "timeout" | "error";
      readonly code?: string;
      readonly elapsedMs: number;
    };

export interface DecideBranch0ElseBranch0ElseBranch0ThenReplyModelInvocation {
  readonly runId: string;
  readonly stepId: "Decide/branch:0/else/branch:0/else/branch:0/then/model:reply";
  readonly profile: "mock";
  readonly instructions: string;
  readonly context: {
    readonly "text": string;
  };
  readonly outputSchema: Readonly<Record<string, unknown>>;
  readonly signal: AbortSignal;
}

export type DecideBranch0ElseBranch0ElseBranch0ThenReplyModelResult =
  | {
      readonly status: "succeeded";
      readonly value: Message;
      readonly usage: {
        readonly input_tokens: number;
        readonly output_tokens: number;
      };
      readonly elapsedMs: number;
    }
  | {
      readonly status: "failed";
      readonly code: string;
      readonly elapsedMs: number;
    };

export interface DecideBranch0ElseBranch0ElseBranch0ElseReplyModelInvocation {
  readonly runId: string;
  readonly stepId: "Decide/branch:0/else/branch:0/else/branch:0/else/model:reply";
  readonly profile: "mock";
  readonly instructions: string;
  readonly context: {
    readonly "text": string;
  };
  readonly outputSchema: Readonly<Record<string, unknown>>;
  readonly signal: AbortSignal;
}

export type DecideBranch0ElseBranch0ElseBranch0ElseReplyModelResult =
  | {
      readonly status: "succeeded";
      readonly value: Message;
      readonly usage: {
        readonly input_tokens: number;
        readonly output_tokens: number;
      };
      readonly elapsedMs: number;
    }
  | {
      readonly status: "failed";
      readonly code: string;
      readonly elapsedMs: number;
    };

export type GuardStepToolInvocation = EchoToolInvocation;
export type GuardStepToolResult = EchoToolResult;
export type GuardStepModelInvocation = DecideBranch0ElseBranch0ElseBranch0ThenReplyModelInvocation | DecideBranch0ElseBranch0ElseBranch0ElseReplyModelInvocation;
export type GuardStepModelResult = DecideBranch0ElseBranch0ElseBranch0ThenReplyModelResult | DecideBranch0ElseBranch0ElseBranch0ElseReplyModelResult;

export interface GuardStepWorkflowContracts {
  readonly "Decide": {
    readonly input: Message;
    readonly output: Message;
    readonly failure: Failure;
  };
}

export type GuardStepWorkflowName = keyof GuardStepWorkflowContracts;
export type GuardStepWorkflowInput<Name extends GuardStepWorkflowName> = GuardStepWorkflowContracts[Name]["input"];
export type GuardStepWorkflowOutput<Name extends GuardStepWorkflowName> = GuardStepWorkflowContracts[Name]["output"];
export type GuardStepWorkflowFailure<Name extends GuardStepWorkflowName> = GuardStepWorkflowContracts[Name]["failure"];

export type GuardStepCapability =
  | "echo";

export interface GuardStepHost {
  readonly schemaVersion: 1;
  readonly workflow?: GuardStepWorkflowName;
  readonly grantedCapabilities: readonly GuardStepCapability[];
  readonly pricing: __GuardStepPricing;
  readonly tools: {
    invoke(request: GuardStepToolInvocation): Promise<GuardStepToolResult>;
  };
  readonly model: {
    generate(request: GuardStepModelInvocation): Promise<GuardStepModelResult>;
  };
}
