// Generated by GuardStep. Do not edit manually.
// Generator: GuardStep 0.1.0-alpha.1
// Source: answer.guard
// Source SHA-256: sha256:fe3ad9060f2195ee4864d21c042a9ff99051ae0b5de2ada39975bdf0e764542c

import type { Pricing as __GuardStepPricing } from "guardstep/runtime";

export type AnswerStatus =
  | "answered"
  | "insufficient_context";

export type FailureCode =
  | "CAPABILITY_DENIED"
  | "SEARCH_TIMEOUT"
  | "TOOL_CALL_FAILED"
  | "TOOL_OUTPUT_INVALID"
  | "MODEL_CALL_FAILED"
  | "MODEL_OUTPUT_INVALID"
  | "CITATION_REQUIRED"
  | "CITATION_FORBIDDEN"
  | "CITATION_UNKNOWN"
  | "COST_LIMIT_EXCEEDED"
  | "DURATION_LIMIT_EXCEEDED";

export interface Question {
  readonly "question": string;
}

export interface Citation {
  readonly "document_id": string;
  readonly "title": string;
  readonly "url": string;
}

export interface Document {
  readonly "id": string;
  readonly "title": string;
  readonly "url": string;
  readonly "content": string;
}

export interface Answer {
  readonly "status": AnswerStatus;
  readonly "text": string;
  readonly "citations": ReadonlyArray<Citation>;
}

export interface DocumentsSearchToolInvocation {
  readonly runId: string;
  readonly stepId: string;
  readonly tool: "documents.search";
  readonly arguments: {
    readonly "question": string;
  };
}

export type DocumentsSearchToolResult =
  | {
      readonly status: "succeeded";
      readonly value: ReadonlyArray<Document>;
      readonly elapsedMs: number;
      readonly eventData?: Readonly<Record<string, unknown>>;
    }
  | {
      readonly status: "failed";
      readonly kind: "timeout" | "error";
      readonly code?: string;
      readonly elapsedMs: number;
    };

export interface AnswerQuestionAnswerModelInvocation {
  readonly runId: string;
  readonly stepId: "AnswerQuestion/model:answer";
  readonly profile: "balanced";
  readonly instructions: string;
  readonly context: {
    readonly "question": string;
    readonly "documents": ReadonlyArray<Document>;
  };
  readonly outputSchema: Readonly<Record<string, unknown>>;
}

export type AnswerQuestionAnswerModelResult =
  | {
      readonly status: "succeeded";
      readonly value: Answer;
      readonly usage: {
        readonly input_tokens: number;
        readonly output_tokens: number;
      };
      readonly elapsedMs: number;
    }
  | {
      readonly status: "failed";
      readonly code: string;
      readonly elapsedMs: number;
    };

export type GuardStepToolInvocation = DocumentsSearchToolInvocation;
export type GuardStepToolResult = DocumentsSearchToolResult;
export type GuardStepModelInvocation = AnswerQuestionAnswerModelInvocation;
export type GuardStepModelResult = AnswerQuestionAnswerModelResult;

export interface GuardStepWorkflowContracts {
  readonly "AnswerQuestion": {
    readonly input: Question;
    readonly output: Answer;
    readonly failure: FailureCode;
  };
}

export type GuardStepWorkflowName = keyof GuardStepWorkflowContracts;
export type GuardStepWorkflowInput<Name extends GuardStepWorkflowName> = GuardStepWorkflowContracts[Name]["input"];
export type GuardStepWorkflowOutput<Name extends GuardStepWorkflowName> = GuardStepWorkflowContracts[Name]["output"];
export type GuardStepWorkflowFailure<Name extends GuardStepWorkflowName> = GuardStepWorkflowContracts[Name]["failure"];

export type GuardStepCapability =
  | "documents.search";

export interface GuardStepHost {
  readonly schemaVersion: 1;
  readonly workflow?: GuardStepWorkflowName;
  readonly grantedCapabilities: readonly GuardStepCapability[];
  readonly pricing: __GuardStepPricing;
  readonly tools: {
    invoke(request: GuardStepToolInvocation): Promise<GuardStepToolResult>;
  };
  readonly model: {
    generate(request: GuardStepModelInvocation): Promise<GuardStepModelResult>;
  };
}
